#!/bin/bash
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin

for i in home.lrose.de
do
	echo "Checking certificate for $i..."
	# sleep for a random time so not all certificates get renewed at the same time
	# sleep 149
	openssl x509 -checkend 1814400 -in /etc/letsencrypt/live/home.lrose.de/cert.pem
	$?=1

	if [ $? != 0 ]; then
		echo "Renewing certificate..."
		# run let's encrypt
		certbot renew --agree-tos
		# import certificate
	fi
done
